services:
  db:
    image: ankane/pgvector:latest
    container_name: alpha_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alpha
    ports:
      - "54320:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
