import { Form } from '@/app/api/upload/form';

export const form: Form = {
  fields: [
    {
      name: 'entity_name',
      label: 'Name of entity/individual',
      description:
        "An entry is required. (For a sole proprietor or disregarded entity, enter the owner's name on line 1, and enter the business/disregarded entity's name on line 2.)",
      type: 'short_text',
      required: true,
      readOnly: false,
      placeholder: '.',
      defaultValue: '',
      options: null,
      validation: null,
      dependency: null,
      group: '.',
      anchors: [
        {
          path: 'keys/1',
        },
      ],
    },
    {
      name: 'business_name',
      label: 'Business name/disregarded entity name',
      description: 'If different from above.',
      type: 'short_text',
      required: false,
      readOnly: false,
      placeholder: '.',
      defaultValue: '',
      options: null,
      validation: null,
      dependency: null,
      group: '.',
      anchors: [
        {
          path: 'keys/2',
        },
      ],
    },
    {
      name: 'tax_classification',
      label: 'Federal tax classification',
      description:
        'Check the appropriate box for federal tax classification of the entity/individual whose name is entered on line 1. Check only one of the following seven boxes.',
      type: 'select_one',
      required: true,
      readOnly: false,
      placeholder: '.',
      defaultValue: '',
      options: [
        {
          value: 'individual_sole_proprietor',
          label: 'Individual/sole proprietor',
          exportValue: ':unselected:',
          anchors: [
            {
              path: 'keys/3',
            },
          ],
        },
        {
          value: 'c_corporation',
          label: 'C corporation',
          exportValue: ':unselected:',
          anchors: [
            {
              path: 'keys/4',
            },
          ],
        },
        {
          value: 's_corporation',
          label: 'S corporation',
          exportValue: ':unselected:',
          anchors: [
            {
              path: 'keys/5',
            },
          ],
        },
        {
          value: 'partnership',
          label: 'Partnership',
          exportValue: ':unselected:',
          anchors: [
            {
              path: 'keys/6',
            },
          ],
        },
        {
          value: 'trust_estate',
          label: 'Trust/estate',
          exportValue: ':unselected:',
          anchors: [
            {
              path: 'keys/7',
            },
          ],
        },
        {
          value: 'llc',
          label: 'LLC',
          exportValue: ':unselected:',
          anchors: [
            {
              path: 'keys/8',
            },
          ],
        },
        {
          value: 'other',
          label: 'Other',
          exportValue: ':unselected:',
          anchors: [
            {
              path: 'keys/9',
            },
          ],
        },
      ],
      validation: null,
      dependency: null,
      group: '.',
      anchors: [
        {
          path: 'pages/1/lines/17',
        },
      ],
    },
    {
      name: 'foreign_partners',
      label: 'Foreign partners, owners, or beneficiaries',
      description: 'Check this box if you have any foreign partners, owners, or beneficiaries.',
      type: 'checkbox',
      required: false,
      readOnly: false,
      placeholder: '.',
      defaultValue: false,
      options: null,
      validation: null,
      dependency: null,
      group: '.',
      anchors: [
        {
          path: 'keys/11',
        },
      ],
    },
    {
      name: 'address',
      label: 'Address',
      description: 'Number, street, and apt. or suite no.',
      type: 'short_text',
      required: true,
      readOnly: false,
      placeholder: '.',
      defaultValue: '',
      options: null,
      validation: null,
      dependency: null,
      group: '.',
      anchors: [
        {
          path: 'keys/13',
        },
      ],
    },
    {
      name: 'city_state_zip',
      label: 'City, state, and ZIP code',
      description: '',
      type: 'short_text',
      required: true,
      readOnly: false,
      placeholder: '.',
      defaultValue: '',
      options: null,
      validation: null,
      dependency: null,
      group: '.',
      anchors: [
        {
          path: 'keys/14',
        },
      ],
    },
    {
      name: 'account_numbers',
      label: 'List account number(s)',
      description: 'Optional',
      type: 'short_text',
      required: false,
      readOnly: false,
      placeholder: '.',
      defaultValue: '',
      options: null,
      validation: null,
      dependency: null,
      group: '.',
      anchors: [
        {
          path: 'keys/15',
        },
      ],
    },
    {
      name: 'exempt_payee_code',
      label: 'Exempt payee code',
      description: 'If any',
      type: 'short_text',
      required: false,
      readOnly: false,
      placeholder: '.',
      defaultValue: '',
      options: null,
      validation: null,
      dependency: null,
      group: '.',
      anchors: [
        {
          path: 'keys/16',
        },
      ],
    },
    {
      name: 'fatca_code',
      label: 'FATCA reporting code',
      description:
        'Exemption from Foreign Account Tax Compliance Act (FATCA) reporting code (if any)',
      type: 'short_text',
      required: false,
      readOnly: false,
      placeholder: '.',
      defaultValue: '',
      options: null,
      validation: null,
      dependency: null,
      group: '.',
      anchors: [
        {
          path: 'keys/17',
        },
      ],
    },
    {
      name: 'social_security_number',
      label: 'Social security number',
      description: '',
      type: 'short_text',
      required: true,
      readOnly: false,
      placeholder: '.',
      defaultValue: '',
      options: null,
      validation: {
        pattern: '\\d{3}-\\d{2}-\\d{4}',
        minLength: null,
        maxLength: null,
        min: null,
        max: null,
        allowedValues: null,
      },
      dependency: null,
      group: '.',
      anchors: [
        {
          path: 'keys/18',
        },
      ],
    },
    {
      name: 'employer_identification_number',
      label: 'Employer identification number',
      description: '',
      type: 'short_text',
      required: false,
      readOnly: false,
      placeholder: '.',
      defaultValue: '',
      options: null,
      validation: {
        pattern: '\\d{2}-\\d{7}',
        minLength: null,
        maxLength: null,
        min: null,
        max: null,
        allowedValues: null,
      },
      dependency: null,
      group: '.',
      anchors: [
        {
          path: 'keys/19',
        },
      ],
    },
    {
      name: 'signature',
      label: 'Signature of U.S. person',
      description: '',
      type: 'signature',
      required: true,
      readOnly: false,
      placeholder: '.',
      defaultValue: '',
      options: null,
      validation: null,
      dependency: null,
      group: '.',
      anchors: [
        {
          path: 'keys/20',
        },
      ],
    },
    {
      name: 'signature_date',
      label: 'Date',
      description: '',
      type: 'date',
      required: true,
      readOnly: false,
      placeholder: '.',
      defaultValue: '',
      options: null,
      validation: null,
      dependency: null,
      group: '.',
      anchors: [
        {
          path: 'keys/21',
        },
      ],
    },
    {
      name: 'social_security_number',
      label: 'Social Security Number (SSN)',
      description: 'Enter your social security number',
      type: 'short_text',
      required: true,
      readOnly: false,
      placeholder: '000-00-0000',
      defaultValue: null,
      options: null,
      validation: {
        pattern: '^\\d{3}-\\d{2}-\\d{4}$',
        minLength: null,
        maxLength: null,
        min: null,
        max: null,
        allowedValues: null,
      },
      dependency: null,
      group: '',
      anchors: [
        {
          path: 'pages/2/lines/4',
        },
      ],
    },
    {
      name: 'individual_taxpayer_identification_number',
      label: 'Individual Taxpayer Identification Number (ITIN)',
      description: 'Enter your individual taxpayer identification number',
      type: 'short_text',
      required: true,
      readOnly: false,
      placeholder: '000-00-0000',
      defaultValue: null,
      options: null,
      validation: {
        pattern: '^\\d{3}-\\d{2}-\\d{4}$',
        minLength: null,
        maxLength: null,
        min: null,
        max: null,
        allowedValues: null,
      },
      dependency: null,
      group: '',
      anchors: [
        {
          path: 'pages/2/lines/5',
        },
      ],
    },
    {
      name: 'adoption_taxpayer_identification_number',
      label: 'Adoption Taxpayer Identification Number (ATIN)',
      description: 'Enter your adoption taxpayer identification number',
      type: 'short_text',
      required: true,
      readOnly: false,
      placeholder: '000-00-0000',
      defaultValue: null,
      options: null,
      validation: {
        pattern: '^\\d{3}-\\d{2}-\\d{4}$',
        minLength: null,
        maxLength: null,
        min: null,
        max: null,
        allowedValues: null,
      },
      dependency: null,
      group: '',
      anchors: [
        {
          path: 'pages/2/lines/5',
        },
      ],
    },
    {
      name: 'employer_identification_number',
      label: 'Employer Identification Number (EIN)',
      description: 'Enter your employer identification number',
      type: 'short_text',
      required: true,
      readOnly: false,
      placeholder: '00-0000000',
      defaultValue: null,
      options: null,
      validation: {
        pattern: '^\\d{2}-\\d{7}$',
        minLength: null,
        maxLength: null,
        min: null,
        max: null,
        allowedValues: null,
      },
      dependency: null,
      group: '',
      anchors: [
        {
          path: 'pages/2/lines/6',
        },
      ],
    },
    {
      name: 'certify_tin',
      label: 'Certify that the TIN you are giving is correct',
      description: 'Check this box if you certify that the TIN provided is correct',
      type: 'checkbox',
      required: false,
      readOnly: false,
      placeholder: '',
      defaultValue: null,
      options: null,
      validation: null,
      dependency: null,
      group: '',
      anchors: [
        {
          path: 'pages/2/lines/30',
        },
      ],
    },
    {
      name: 'certify_not_subject_to_backup_withholding',
      label: 'Certify not subject to backup withholding',
      description: 'Check this box if you are not subject to backup withholding',
      type: 'checkbox',
      required: false,
      readOnly: false,
      placeholder: '',
      defaultValue: null,
      options: null,
      validation: null,
      dependency: null,
      group: '',
      anchors: [
        {
          path: 'pages/2/lines/32',
        },
      ],
    },
    {
      name: 'claim_exemption_from_backup_withholding',
      label: 'Claim exemption from backup withholding',
      description: 'Check this box if you are claiming an exemption from backup withholding',
      type: 'checkbox',
      required: false,
      readOnly: false,
      placeholder: '',
      defaultValue: null,
      options: null,
      validation: null,
      dependency: null,
      group: '',
      anchors: [
        {
          path: 'pages/2/lines/33',
        },
      ],
    },
  ],
};
